[project]
name = "MultiAgentChatAI"
version = "0.1.0"
description = "Conversational AI project based on multi-agent architecture."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "autogen>=0.5.1",
    "fastapi>=0.115.6",
    "pydantic-settings>=2.6.1",
    "pydantic>=2.10.3",
    "python-dotenv>=1.0.1",
    "redis>=5.2.1",
    "uvicorn>=0.32.1",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.8.2",
]
